# Generated by Django 5.0.6 on 2024-11-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_electricitybill_created_date_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypayment',
            name='pending_from',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='pending_to',
        ),
    ]
